services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    container_name: web
    # depends_on:
    #   - backend
    env_file:
      - ./.env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    ports:
      - "${FRONTEND_HTTP_PORT:-4000}:80"
    restart: unless-stopped